# Generated by Django 2.2.6 on 2019-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='BTC',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='ETH',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
