# Generated by Django 2.2.6 on 2019-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0002_auto_20191101_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BTC',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ETH',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LTC',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Wallets',
        ),
    ]
